# mysql service
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcoffee
      MYSQL_USER: tcoffee
      MYSQL_PASSWORD: tcoffee

    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
